language:
  - cpp

sudo:
  - true

os:
  - linux
  - osx

dist:
  - bionic

osx_image:
  - xcode11

addons:
  apt:
    packages:
      - cmake
      - python3-pip
      - libpython3-dev
  brew:
    packages:
      - cmake
      - python

install:
  - which python
  - python --version
  - which python3
  - python3 --version
  - pip3 install -U spacy
  - pip3 install -U --upgrade cryptography
  - sudo python3 -m spacy download en_core_web_sm

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make -s
  - ctest --output-on-failure 
